version: "3"

vars:
  PROJECT_DIR:
    sh: pwd

includes:
  brew: ./tasks/brew.yaml
  mise: ./tasks/mise.yaml
  links:
    taskfile: ./tasks/symlink.yaml
    flattern: true
  neovim:
    taskfile: ./tasks/nvim.yaml
    flatten: true
  git:
    taskfile: ./tasks/git.yaml
  zed: ./tasks/zed.yaml
  prepare: ./tasks/prepare.yaml
  macos: ./tasks/macos.yaml
  ghostty: ./tasks/ghostty.yaml

tasks:
  default:
    desc: Show commands
    cmds:
      - task -l --sort none
