# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  PROJECT_DIR:
    sh: pwd
  GIT_DIR: .config/git

tasks:
  setup:
    deps: [directories]
    cmds:
      - task: config
      - task: ignore
      - task: template

  directories:
    internal: true
    desc: Check Git dir exists
    cmds:
      - '[[ ! -d ~/{{.GIT_DIR}} ]] && mkdir -p ~/{{.GIT_DIT}} || echo "~/{{.GIT_DIR}} is already exist"'
      -
    silent: true

  config:
    desc: Create Symbolic Link of git config
    cmds:
      # .gitconfig
      - ln -s {{.PROJECT_DIR}}/HOME/.config/git/.gitconfig ~/.gitconfig
    preconditions:
      - sh: '[ ! -L ~/.gitconfig ]'
        msg: "~/.gitconfig is already exists"

  ignore:
    desc: Create Symbolic Link of git global ignore
    deps: [directories]
    cmds:
      # Git Global Ignore
      - ln -s {{.PROJECT_DIR}}/HOME/.config/git/ignore ~/.config/git/ignore
    preconditions:
      - sh: '[ ! -L ~/.config/git/ignore ]'
        msg: "~/.config/git/ignore is already exists"

  template:
    desc: Create Symbolic Link of commit_template
    deps: [directories]
    cmds:
      # Git Commit Template
      - ln -s {{.PROJECT_DIR}}/HOME/.config/git/.commit_template ~/.config/git/.commit_template
    preconditions:
      - sh: '[ ! -L ~/.config/git/.commit_template ]'
        msg: "~/.config.git/.commit_template is already exists"

  lazygit:
    desc: Create Symbolic Link for lazygit
    deps: [directories]
    cmds:
      # Lazygit Config File
      - ln -s {{.PROJECT_DIR}}/HOME/.config/lazygit ~/.config/lazygit
    preconditions:
      - sh: '[ ! -L ~/.config/lazygit ]'
        msg: "~/.config/lazygit is already exists"
