# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  PROJECT_DIR:
    sh: pwd
  YAZI_DIR: .config/yazi
tasks:
  deploy:
    desc: Create Symbolic Links
    preconditions:
      - sh: '[[ ! -L ~/.config/yazi/ ]]'
        msg: "~/.config/yazi is already exists"
    cmds:
      - ln -s {{.PROJECT_DIR}}/HOME/{{.YAZI_DIR}} ~/{{.YAZI_DIR}}
      - git clone https://github.com/BennyOe/tokyo-night.yazi.git ~/.config/yazi/flavors/tokyo-night.yazi
      - git clone https://github.com/bennyyip/gruvbox-dark.yazi.git ~/.config/yazi/flavors/gruvbox-dark.yazi
      - git clone https://github.com/kmlupreti/ayu-dark.yazi.git ~/.config/yazi/flavors/ayu-dark.yazi
