require("plugins.setup")
require("base")
require("keymaps")
require("options")

require("plugins.github-theme")
require("plugins.fern")
require("plugins.fern-renderer")
require("plugins.neoterm")
require("plugins.telescope")
require("plugins.coc")
require("plugins.todo-comments")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.indent")
--require("plugins.other-nvim")
require("plugins.nvim-autopairs")
