[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# ファイラプラグイン
repo = 'lambdalisue/fern.vim'
# Ctrl + nでファイルツリーを表示/非表示をトグルする
hook_add = '''
    nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''
# j, k   :上下に移動する
# l      :フォルダを展開する、ファイルを開く
# h      :フォルダを閉じる
# e      :ファイルを開く
# E      :垂直分割してファイルを開く
# t      :新規タブでファイルを開く
# Ctrl+m : フォルダを開く
# Ctrl+h : 親ディレクトリに移動する
# N      : ファイルを新規作成する
# K      : ディレクトリを新規作成する
# D      : ファイルを削除する
# m      : ファイルを移動する
# R      : ファイル名を変更する
# -      : ファイルを選択する
# C      : ファイルをコピーする
# P      : ペーストする
# M      : ファイルをコピーし、ペーストした時に元のファイルを削除する
# y      : ファイルパスをコピーする
# z      : ファイル名に合わせてウィンドウ幅を広げる
# !      : 隠しファイルを表示/非表示する

[[plugins]]
# skkeletonの依存(denoを利用できるようにするプラグイン)
repo = 'vim-denops/denops.vim'

[[plugins]]
# 日本語入力プラグイン
repo = 'vim-skk/skkeleton'

[[plugins]]
# Fernのファイルツリーにgitの差分が表示できるプラグイン
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
# ファイルツリーにアイコンを表示するためのフォントプラグイン
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
    let g:fern#renderer = 'hack-nerd-font'
'''

[[plugins]]
# ファイルツリーのアイコンに色をつけるプラグイン
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
    " アイコンに色をつける
    augroup my-glyph-palette
      autocmd! *
      autocmd FileType fern call glyph_palette#apply()
      autocmd FileType nerdtree,startify call glyph_palette#apply()
    augroup END
'''

[[plugins]]
# ファイル更新時にタイムスタンプをセットする
repo = 'leoco/autodate.vim'

[[plugins]]
# 自作snippetを作成する
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
# neovimの非同期jobを制御する
repo = 'prabirshrestha/async.vim'

[[plugins]]
# Vim scriptで実装されたLSPプラグイン
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
# vimのステータスバーを色付けして表示する
repo = 'itchyny/lightline.vim'

[[plugins]]
# coc-vimと連携して関数や変数へジャンプできるプラグイン
repo = 'liuchengxu/vista.vim'

[[plugins]]
# vim-quickrunをnvimで実行できるようにするプラグイン
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]]
# マイクロコードを実行するvim用プラグイン
repo = 'thinca/vim-quickrun'

[[plugins]]
# Golang用のプラグイン
repo = 'fatih/vim-go'

[[plugins]]
# Vim上でgitを操作できるプラグイン
repo = 'lambdalisue/gina.vim'

[[plugins]]
# Syntax highlightできるプラグイン
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
# テキストを囲う操作を行えるようにするプラグイン
repo = 'machakann/vim-sandwich'
[[plugins]]
# VScodeの機能を使用できるようにするプラグイン
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add =  '''
    nnoremap [coc] <Nop>
    nmap <space>c [coc]
    nmap <silent> [coc]f <Plug>(coc-format)
    nmap <silent> [coc]<space> :<C-u>CocList<cr>
    nmap <silent> [coc]rn <Plug>(coc-rename)
    nmap <silent> [coc]h :<C-u>call CocAction('doHover')<cr>
    nmap <silent> [coc]d <Plug>(coc-definition)
    nmap <silent> [coc]rf <Plug>(coc-references)
'''
